const $=id=>document.getElementById(id),gtColor='#087f5b',predColor='#c45a13';
let current=null,camera=0,images=[],threshold=.55,summary=null,requested=-1,generation=0,abort=null,events=[],event=null;
const fmt=(n,d=2)=>Number.isFinite(n)?n.toFixed(d):'—';
function child(){return $('replay').contentWindow;}
function jump(i){const doc=child().document,s=doc.getElementById('scrubber');if(!s)return;s.value=Math.max(0,Math.min(196,i));s.dispatchEvent(new Event('input',{bubbles:true}));}
function syncThreshold(){const doc=child().document,input=doc.getElementById('confidence');if(input){input.value=threshold;input.dispatchEvent(new Event('input',{bubbles:true}));}}
function pathLines(ctx,edges,color){ctx.strokeStyle=color;ctx.lineWidth=1.25;for(const edge of edges){ctx.beginPath();let active=false;for(const p of edge){if(!p){active=false;continue;}if(active)ctx.lineTo(...p);else ctx.moveTo(...p);active=true;}ctx.stroke();}}
function drawCamera(){if(!current||!images[camera])return;const cv=$('camera'),ctx=cv.getContext('2d');ctx.clearRect(0,0,cv.width,cv.height);ctx.drawImage(images[camera],0,0,704,256);if($('lidar').checked){for(const [u,v,d] of current.projection.lidar[camera]){ctx.fillStyle=`hsl(${210-Math.min(d,60)*2},90%,65%)`;ctx.fillRect(u-1,v-1,2,2);}}if($('show-pred').checked)current.projection.predictions.forEach((views,i)=>{if(current.predictions.scores[i]>=threshold)pathLines(ctx,views[camera],predColor);});if($('show-gt').checked)current.projection.targets.forEach(views=>pathLines(ctx,views[camera],gtColor));$('image-source').textContent=current.predictions.image_paths[camera]+' · exact 704 × 256 model input';}
const colors=['#aebbc4','#d1dacf','#99b4a7'];
function bev(cv,truth){const ctx=cv.getContext('2d'),size=cv.width,scale=size/80;ctx.clearRect(0,0,size,size);ctx.fillStyle='#edf2f6';ctx.fillRect(0,0,size,size);const road=truth?current.targets.road:current.predictions.road;for(let y=0;y<160;y++)for(let x=0;x<160;x++){const c=road[y][x];if(c<0||(!truth&&!current.predictions.road_visible?.[y]?.[x]))continue;ctx.fillStyle=colors[c];ctx.fillRect((159-y)*size/160,(159-x)*size/160,size/160+.2,size/160+.2);}const screen=(x,y)=>[(40-y)*scale,(40-x)*scale];function box(b,color){const [x,y,z,l,w,h,a]=b;const c=Math.cos(a),s=Math.sin(a);ctx.strokeStyle=color;ctx.lineWidth=1.4;ctx.beginPath();for(const [j,[sx,sy]] of [[1,1],[-1,1],[-1,-1],[1,-1],[1,1]].entries()){const p=screen(x+c*sx*l/2-s*sy*w/2,y+s*sx*l/2+c*sy*w/2);j?ctx.lineTo(...p):ctx.moveTo(...p);}ctx.stroke();const start=screen(x,y),end=screen(x+c*l/2,y+s*l/2);ctx.beginPath();ctx.moveTo(...start);ctx.lineTo(...end);ctx.stroke();}current.targets.boxes.forEach(b=>box(b,gtColor));if(!truth)current.predictions.boxes.forEach((b,i)=>{if(current.predictions.scores[i]>=threshold)box(b,predColor);});ctx.fillStyle='#243640';const ego=screen(0,0);ctx.fillRect(ego[0]-3,ego[1]-5,6,10);ctx.font='10px Segoe UI';ctx.fillText('Forward',size/2-18,11);}
function drawTable(){const matches=current.matches[String(threshold)],body=$('objects');body.replaceChildren();for(const r of matches.targets){const g=current.targets.boxes[r.gt_index],p=r.matched_prediction===null?null:current.predictions.boxes[r.matched_prediction];const row=document.createElement('tr');if(!p)row.className='missed';const vals=[r.gt_id,r.label===0?'Car':'Person',p?r.track_id:'Missed',fmt(r.score),r.center_error_world?fmt(Math.hypot(...r.center_error_world))+' m':'—',g.slice(3,6).map(x=>fmt(x)).join(' × '),p?p.slice(3,6).map(x=>fmt(x)).join(' × '):'—',fmt(g[6]*180/Math.PI,1)+'° / '+(p?fmt(p[6]*180/Math.PI,1)+'°':'—'),fmt(r.best_iou)];for(const text of vals){const td=document.createElement('td');td.textContent=text;row.append(td);}body.append(row);}const counts=matches.prediction_status.reduce((s,k)=>(s[k]=(s[k]||0)+1,s),{});$('frame-summary').textContent=`${matches.targets.length} supported labels · ${counts.matched||0} matched predictions · ${counts.scored_unmatched||0} scored unmatched · ${counts.unassessed||0} unassessed · ${counts.below_threshold||0} below cutoff`;
const fields={frame:current.frame_id,timestamp:current.timestamp,provenance:current.provenance,boxes:{ground_truth:current.targets.boxes,predicted:current.predictions.boxes},dataset_ids:current.targets.instance_ids,track_ids:current.predictions.track_ids,scores:current.predictions.scores,calibration:current.calibration,array_shapes:{road:[160,160],depth_target:[4,32,88],detection_valid:[2,160,160]},note:'Full arrays are in paired JSON; the NPZ download is the original compiled cache.'};$('raw-data').textContent=JSON.stringify(fields,null,2);}
function draw(){drawCamera();if(current){bev($('ground-truth'),true);bev($('predicted-ground'),false);drawTable();}}
function updateStats(){if(!summary)return;const s=summary.thresholds[String(threshold)],c=s.counts;$('consistency-summary').replaceChildren();for(const [key,label] of [['supported_adjacent_pairs','supported car pairs'],['disappeared','match lost'],['reappeared','match regained'],['track_id_changes','track ID changes'],['matched_both','matched in both']]){const el=document.createElement('div');el.className='count';const strong=document.createElement('strong'),span=document.createElement('span');strong.textContent=c[key]||0;span.textContent=label;el.append(strong,span);$('consistency-summary').append(el);}events=s.events;$('event').replaceChildren(new Option('Choose an event',''));events.forEach((e,k)=>$('event').add(new Option(`Frames ${e.previous_index+1} → ${e.index+1}, car ${e.gt_id}: ${e.kind==='matched_both'?(e.track_id_changed?'track ID change':'geometry jump'):e.kind}`,String(k))));event=null;$('event-description').textContent='Failures are selected by numerical rules, not by how good a scene looks.';}
async function load(index){requested=index;const serial=++generation;abort?.abort();abort=new AbortController();document.body.classList.add('loading');$('sync').textContent='Loading matching reference…';try{const r=await fetch(`/reference/frame?index=${index}`,{signal:abort.signal});if(!r.ok)throw new Error(`Reference returned ${r.status}`);const data=await r.json();const loaded=await Promise.all([0,1,2,3].map(c=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>im.naturalWidth===704&&im.naturalHeight===256?resolve(im):reject(new Error('Wrong camera input dimensions'));im.onerror=()=>reject(new Error('Camera input missing'));im.src=`/api/image?index=${index}&camera=${c}`;})));if(serial!==generation)return;current=data;images=loaded;draw();$('frame').value=index;$('position').textContent=`${index+1} / 197 · source ${data.frame_id}`;$('sync').textContent='Same frame verified';document.body.classList.remove('loading');for(const [id,path] of [['json-download','frame'],['cache-download','targets'],['lidar-download','lidar']])$(id).href=`/reference/${path}?index=${index}`;$('error').hidden=true;window.inspectionState={index,frame_id:data.frame_id,threshold,reference_ready:true};}catch(e){if(e.name==='AbortError'||serial!==generation)return;$('sync').textContent='Reference unavailable';$('error').textContent=e.message;$('error').hidden=false;requested=-1;}}
$('back').onclick=()=>jump((current?.index||0)-1);$('forward').onclick=()=>jump((current?.index||0)+1);$('frame').oninput=()=>jump(Number($('frame').value));$('threshold').onchange=()=>{threshold=Number($('threshold').value);syncThreshold();updateStats();draw();if(window.inspectionState)window.inspectionState.threshold=threshold;};document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{camera=Number(b.dataset.camera);document.querySelectorAll('[data-camera]').forEach(x=>x.classList.toggle('selected',x===b));drawCamera();});for(const id of ['lidar','show-gt','show-pred'])$(id).onchange=drawCamera;
$('event').onchange=()=>{event=events[Number($('event').value)];if($('event').value===''){event=null;return;}$('event-description').textContent=JSON.stringify(event);jump(event.previous_index);};$('event-before').onclick=()=>{if(event)jump(event.previous_index);};$('event-after').onclick=()=>{if(event)jump(event.index);};
fetch('/reference/consistency').then(r=>r.json()).then(r=>{summary=r;updateStats();}).catch(e=>{$('error').textContent=e.message;$('error').hidden=false;});
setInterval(()=>{try{const state=child().sceneReplayTiming?.snapshot().context;if(state&&Number.isInteger(state.frame_index)&&state.frame_index!==requested)load(state.frame_index);const input=child().document.getElementById('confidence');if(input&&Number(input.value)!==threshold)syncThreshold();}catch{}},100);

// Observe the child's frame label before paint so old references are hidden as soon as the prediction changes.
$('replay').addEventListener('load',()=>{const label=child().document.getElementById('sequence');if(label)new MutationObserver(()=>{const i=child().sceneReplayTiming?.snapshot().context.frame_index;if(Number.isInteger(i)&&i!==requested)load(i);}).observe(label,{childList:true,subtree:true,characterData:true});});
